export const articles = [
  // 移动
  {
    title: '中国移动福气卡',
    desc: '39元240G+2000分钟，福建五城专属。',
    url: '/article/card/fuqi-card.html',
    tag: '39元240G',
    carrier: '移动',
  },
  {
    title: '中国移动黄鹤卡',
    desc: '39元150G流量，仅发湖北七城。',
    url: '/article/card/huanghe-card.html',
    tag: '39元150G',
    carrier: '移动',
  },
  {
    title: '中国移动庐州卡',
    desc: '39元160G+100分钟+100短信。',
    url: '/article/card/luzhou-card.html',
    tag: '39元160G',
    carrier: '移动',
  },
  {
    title: '中国移动水仙卡',
    desc: '29元230G+500分钟，福建五城专属。',
    url: '/article/card/shuixian-card.html',
    tag: '29元230G',
    carrier: '移动',
  },
  {
    title: '中国移动知意卡',
    desc: '39元55G通用流量，48个月合约。',
    url: '/article/card/zhiyi-card.html',
    tag: '39元55G',
    carrier: '移动',
  },
  // 联通
  {
    title: '中国联通大尧卡',
    desc: '39元180G+200分钟，12个月优惠期。',
    url: '/article/card/dayao-card.html',
    tag: '39元180G',
    carrier: '联通',
  },
  {
    title: '中国联通长汀卡',
    desc: '首月49元370G，江西专属。',
    url: '/article/card/changting-card.html',
    tag: '370G',
    carrier: '联通',
  },
  {
    title: '中国联通飞驰卡',
    desc: '39元200G+300分钟，先激活后发货。',
    url: '/article/card/feichi2-card.html',
    tag: '39元200G',
    carrier: '联通',
  },
  {
    title: '中国联通飞辰卡',
    desc: '39元155G+100分钟，赠360G/年。',
    url: '/article/card/feichen-card.html',
    tag: '39元155G',
    carrier: '联通',
  },
  {
    title: '中国联通方圆卡',
    desc: '39元240G+200分钟，长期套餐。',
    url: '/article/card/fangyuan-card.html',
    tag: '39元240G',
    carrier: '联通',
  },
  {
    title: '中国联通飞雀卡',
    desc: '39元150G+200分钟，赠4年会员。',
    url: '/article/card/feique-card.html',
    tag: '39元150G',
    carrier: '联通',
  },
  {
    title: '联通定瓷卡',
    desc: '39元200G+200分钟，可发全国。',
    url: '/article/card/dingci-card.html',
    tag: '39元200G',
    carrier: '联通',
  },
  {
    title: '中国联通飞霄卡',
    desc: '29元150G+200分钟，赠视频会员。',
    url: '/article/card/feixiao-card.html',
    tag: '29元150G',
    carrier: '联通',
  },
  {
    title: '中国联通飞继卡',
    desc: '29元280G+200分钟，首月全量全价。',
    url: '/article/card/feiji-card.html',
    tag: '29元280G',
    carrier: '联通',
  },
  {
    title: '中国联通飞芬卡',
    desc: '39元200G+200分钟，600元封顶。',
    url: '/article/card/feifen-card.html',
    tag: '39元200G',
    carrier: '联通',
  },
  {
    title: '中国联通飞素卡',
    desc: '39元240G+200分钟，首月全量全价。',
    url: '/article/card/feisu-card.html',
    tag: '39元240G',
    carrier: '联通',
  },
  {
    title: '中国联通飞希卡',
    desc: '29元180G+100分钟，首月半量半价。',
    url: '/article/card/feixi-card.html',
    tag: '29元180G',
    carrier: '联通',
  },
  {
    title: '中国联通飞焱卡',
    desc: '29元180G+100分钟，首月半量半价。',
    url: '/article/card/feiyan-card.html',
    tag: '29元180G',
    carrier: '联通',
  },
  {
    title: '中国联通活力卡',
    desc: '39元150G+200分钟，赠会员N选1。',
    url: '/article/card/huoli-card.html',
    tag: '39元150G',
    carrier: '联通',
  },
  {
    title: '中国联通极速卡',
    desc: '39元550G+300分钟，仅发四川。',
    url: '/article/card/jisu-card.html',
    tag: '39元550G',
    carrier: '联通',
  },
  {
    title: '中国联通康定卡',
    desc: '首月1元500G，四川专属。',
    url: '/article/card/kangding-card.html',
    tag: '500G',
    carrier: '联通',
  },
  {
    title: '中国联通南开卡',
    desc: '29元100G+200分钟，重庆专属。',
    url: '/article/card/nankai-card.html',
    tag: '29元100G',
    carrier: '联通',
  },
  {
    title: '中国联通上坎卡',
    desc: '39元190G+200分钟，重庆专属。',
    url: '/article/card/shangkan-card.html',
    tag: '39元190G',
    carrier: '联通',
  },
  {
    title: '中国联通洪崖卡',
    desc: '19元100G+200分钟，12个月优惠。',
    url: '/article/card/hongya-card.html',
    tag: '19元100G',
    carrier: '联通',
  },
  {
    title: '联通广绣卡',
    desc: '39元155G+100分钟，可发广东。',
    url: '/article/card/guangxiu-card.html',
    tag: '39元155G',
    carrier: '联通',
  },
  {
    title: '中国联通灯影卡',
    desc: '首月免费，39元240G+50分钟，四川专属。',
    url: '/article/card/dengying-card.html',
    tag: '39元240G',
    carrier: '联通',
  },
  {
    title: '中国联通飞翅卡',
    desc: '39元300G+100分钟，需搭配路由器设备。',
    url: '/article/card/feichi-card.html',
    tag: '39元300G',
    carrier: '联通',
  },
  {
    title: '中国联通飞倾卡',
    desc: '39元300G+100分钟，468元包年。',
    url: '/article/card/feiqin-card.html',
    tag: '39元300G',
    carrier: '联通',
  },
  {
    title: '中国联通飞塘卡',
    desc: '39元200G+300分钟，先激活后发货。',
    url: '/article/card/feitang-card.html',
    tag: '39元200G',
    carrier: '联通',
  },
  // 电信
  {
    title: '中国电信汉绣卡',
    desc: '39元130G+30G定向+200分钟，仅限湖北四城。',
    url: '/article/card/hanxiu-card.html',
    tag: '39元160G',
    carrier: '电信',
  },
  {
    title: '中国电信敬亭卡',
    desc: '39元150G+100分钟，48个月优惠期。',
    url: '/article/card/jingting-card.html',
    tag: '39元150G',
    carrier: '电信',
  },
  {
    title: '中国电信云朵卡',
    desc: '39元180G+200分钟，无合约期。',
    url: '/article/card/yunduo-card.html',
    tag: '39元180G',
    carrier: '电信',
  },
  {
    title: '中国电信泰山卡',
    desc: '38元190G+300分钟，无合约期。',
    url: '/article/card/taishan-card.html',
    tag: '38元190G',
    carrier: '电信',
  },
  {
    title: '中国电信云梦卡',
    desc: '39元160G+200分钟，仅发湖北七城。',
    url: '/article/card/yunmeng-card.html',
    tag: '39元160G',
    carrier: '电信',
  },
  {
    title: '中国电信知信卡',
    desc: '39元60G通用，只发广东。',
    url: '/article/card/zhixin-card.html',
    tag: '39元60G',
    carrier: '电信',
  },
  // 广电
  {
    title: '中国广电飞狮卡',
    desc: '29元192G通用，首月免费。',
    url: '/article/card/feishi-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电茯苓卡',
    desc: '29元200G通用，可办副卡。',
    url: '/article/card/fuling-card.html',
    tag: '29元200G',
    carrier: '广电',
  },
  {
    title: '中国广电欢马卡',
    desc: '29元192G通用，首月免费。',
    url: '/article/card/huanma-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电巨量卡',
    desc: '29元192G通用，长期套餐。',
    url: '/article/card/juliang-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电骏马卡',
    desc: '29元192G通用，首月免月租。',
    url: '/article/card/junma-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电天马卡',
    desc: '29元192G通用，可发全国。',
    url: '/article/card/tianma-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电奔马卡',
    desc: '39元60G通用，可办副卡。',
    url: '/article/card/benma-card.html',
    tag: '39元60G',
    carrier: '广电',
  },
  {
    title: '中国广电长安卡',
    desc: '29元100G+100分钟，仅限陕西。',
    url: '/article/card/changan-card.html',
    tag: '29元100G',
    carrier: '广电',
  },
  {
    title: '中国广电秦风卡',
    desc: '38元190G+300分钟，只发陕西四城。',
    url: '/article/card/qinfeng-card.html',
    tag: '38元190G',
    carrier: '广电',
  },
  {
    title: '中国广电闽南卡',
    desc: '39元180G+150分钟，仅发福建。',
    url: '/article/card/minnan-card.html',
    tag: '39元180G',
    carrier: '广电',
  },
  {
    title: '中国广电飞狮卡2.0',
    desc: '29元192G通用，首月免费，最长60个月。',
    url: '/article/card/feishi-v2-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电飞狮卡3.0',
    desc: '29元192G通用，首月免费，最长60个月。',
    url: '/article/card/feishi-v3-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电飞狮卡4.0',
    desc: '29元192G通用，首月免费，最长60个月。',
    url: '/article/card/feishi-v4-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  {
    title: '中国广电飞狮卡5.0',
    desc: '29元192G通用，首月免费，最长60个月。',
    url: '/article/card/feishi-v5-card.html',
    tag: '29元192G',
    carrier: '广电',
  },
  // 指南
  // { title: '流量卡怎么选不踩坑', desc: '四大运营商对比、选卡四步法、常见问题。', url: '/article/card/sim-card-guide.html', tag: '选卡指南', carrier: '指南' }
]
